import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import Layout2 from "~/components/Layout2";
import RainbowKit from "~/components/RainbowKit";
import { ParticleConnectkit } from "~/components/KonnectKit";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        {/* <Layout2>{children}</Layout2> */}
        {/* <Layout2> */}
        <ParticleConnectkit>{children}</ParticleConnectkit>
        {/* </Layout2> */}
        {/* <RainbowKit /> */}
      </body>
    </html>
  );
}
